language: python
virtualenv:
  system_site_packages: true
python:
  - "2.6"
before_install:
  - sudo apt-get install python-lxml
services:
  - redis
install: 
  - python setup.py install
before_install:
  - sudo apt-get install python-dev libevent-dev
  - pip install flake8
script:
  - python setup.py test
  - flake8 .
