language: python
python:
  - "2.6"
install: 
  - pip install git+ssh://git@github.com/openlabs/nereid.git
  - python setup.py install
before_install: "sudo apt-get install python-dev libevent-dev"
script: python setup.py test
