language: python
virtualenv:
  system_site_packages: true
python:
  - "2.6"
before_install:
  - sudo apt-get install python-lxml
install: 
  - pip install git+ssh://git@github.com/openlabs/nereid.git@2.4
  - python setup.py install
before_install: "sudo apt-get install python-dev libevent-dev"
script: python setup.py test
