language: python
python:
  - "2.7"
services:
  - redis
install: 
  - python setup.py install
before_install:
  - sudo apt-get install python-dev libevent-dev
  - pip install flake8
script:
  - python setup.py test
  - flake8 .
